### ISSUE TITLE
Comments tries to query the wrong table

### ISSUE THREAD

**Issue by mord0d** [xenocrat/chyrp-lite#230] opened 2023-11-22 22:35 UTC
- **Chyrp Lite:** 2023.03
- **PHP:** 8.2.12
- **Database:** PostgreSQL 16.1
- **nginx:** 1.24.0
- **OS:** FreeBSD 14.0-RELEASE-p0, amd64

Clean URLs enabled.

When I try to access to a single comment by `/blog/comment/2/`, it returns an error:

```
Error
Database error: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = integer LINE 3: WHERE ("cl_pages".url IN ('comment', 2)) ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts.
```

It tries to query the `pages` (`cl_pages`) table, not the `comments` (`cl_comments`).

Query string:

```
SELECT "cl_pages".*
FROM "cl_pages"
WHERE ("cl_pages".url IN ('comment', 2))
ORDER BY "cl_pages".id DESC
```

Parameters:

```
Array
(
)
```

Backtrace:

```
includes/class/Query.php on line 192
includes/class/Query.php on line 116
includes/class/SQL.php on line 179
includes/class/SQL.php on line 250
includes/class/Model.php on line 347
includes/model/Page.php on line 54
includes/model/Page.php on line 346
includes/controller/Main.php on line 168
includes/class/Route.php on line 78
includes/class/Route.php on line 357
includes/class/Route.php on line 357
```

Is my setup incorrect or is it a bug?

**Comment by xenocrat** [comment] 2023-11-22 23:41
Hello there,

The behaviour is correct, but the bug is not intended. 😉

The behaviour: when clean URLs are enabled, Chyrp Lite will check URLs to see if they route to a page. You could decide to create a page called "comments" with another child page called "2", and then the clean URL to reach it would be /comments/2/. That would be weird, but someone might do it.

The bug: looks like you must be using PostgreSQL. You've found a bug in Chyrp Lite that's causing it to try comparing an integer (2) with the contents of the page URL column (VARCHAR).

I'll look into how this can be fixed. Thank you for the report and sorry for the inconvenience.

**Comment by mord0d** [comment] 2023-11-23 00:17
> looks like you must be using PostgreSQL

Sorry… Yes, it's PostgreSQL 16.1.

> Chyrp Lite will check URLs to see if they route to a page. You could decide to create a page called "comments" with another child page called "2", and then the clean URL to reach it would be /comments/2/.

```json
"routes": {
    "tag/(name)/": "tag",
    "category/(name)/": "category",
    "comment/(id)/": "comment",
},
```

`/blog/tag/<tag_name>/` and `/blog/category/<category_name>/` works fine, `/blog/comment/<comment_id>/` does not work (even if a comment with requested ID exists).

I noticed that every theme contains `pages/tag.twig` and `pages/category.twig`, but no `pages/comment.twig`, can this be the key to such behavior?

**Comment by xenocrat** [comment] 2023-11-23 09:27
No, the issue is simply in how the values are being passed to PostgreSQL for the queey. MySQL and SQLite are happy to compare integer 2 with a string of text - they just coerce the integer 2 to the text '2', but PostgreSQL won't do that.

You don't need a twig template for displaying a comment because the route responder just redirects to the post the comment is attached to: for example, if comment IS 2 was added to post ID 5, you'll be redirected to view that post using the twig template view twig.

I've got some thoughts about how to fix the query issue, which I'll implement in the next few days.

**Comment by mord0d** [comment] 2023-11-23 12:21
> You don't need a twig template for displaying a comment because the route responder just redirects to the post the comment is attached to: for example, if comment ID 2 was added to post ID 5, you'll be redirected to view that post using the twig template view.twig.

Oh, I see. Thanks. No PHP knowledge at all, so I didn't check the code. ☺

> I've got some thoughts about how to fix the query issue, which I'll implement in the next few days.

Thanks!

**Comment by xenocrat** [comment] 2024-01-15 11:37
Should be fixed in the latest release.

**Closed by xenocrat** 2024-01-15 11:37 UTC
Labels: bug, willfix
