### ISSUE TITLE
Bug: Setting Feed to "RSS" totally crashes the site (500)

### ISSUE THREAD

**Issue by Tagirijus** [xenocrat/chyrp-lite#174] opened 2022-11-27 17:42 UTC
Hey there,

since version _2022.03_ when setting the feed to type "RSS", the site suddenly only gives 500 errors. Can you reproduce? Any ways of giving you more debbuging information?

**Comment by Tagirijus** [comment] 2022-11-27 18:16
Also something bigger broke somehow ... now I cannot even roll back to the previous version. I backed up the SQL database and the mentioned folders and also my own theme I made. Loaded version _2022.02_ up again, yet it still is broken somehow and says `This resource is temporarily unable to serve your request.`.

**Comment by xenocrat** [comment] 2022-11-27 19:04
Hello there,

Sorry about that. It's fixed now in the develop branch. You second issue is caused by the file _includes/upgrading.lock_; running _upgrade.php_ at any time will remove this file and "unlock" your installation.

**Comment by Tagirijus** [comment] 2022-11-27 19:17
Thanks for the information. I will keep this in mind. Good to know! And thanks for mantaining this whole project and beeing so responsive! (=

**Closed** 2022-11-27 22:01 UTC
