### ISSUE TITLE
Failed to rename tag which contains Asian characters

### ISSUE THREAD

**Issue by cuixiping** [xenocrat/chyrp-lite#257] opened 2024-05-20 08:49 UTC
# ENV:
- PHP version: 8.3
- Database: MariaDB 10.4

# Steps
1. Create a new post with Asian characters tag, for example `文字`.
1. Go to tags manager, rename the tag.
2. There is no change when back to tags list.

# My fix

I solved it by doubling the backslashes in `"tags.php"`. I am not very sure it's correct or not.

```php
            $results = SQL::current()->select(
                tables:"post_attributes",
                fields:"post_id",
                conds:array(
                    "name" => "tags",
---                 "value LIKE" => $this->tags_name_match($_POST['original'])
+++                 "value LIKE" => str_replace("\\","\\\\",$this->tags_name_match($_POST['original']))
                )
            )->fetchAll();
```

**Comment by xenocrat** [comment] 2024-05-20 09:51
Thanks for the report. I see the problem: the tag names are stored as JSON, which will encode any non-ASCII character as a Unicode codepoint using the hex notation "\uXXXXXX". We need to tell the RDBMS we are searching for a literal backslash there.

You're solution is fine for a quick fix, but I've added a commit to do this in a more correct way. It's still not working right on PostgreSQL - I need to investigate that further.

**Comment by xenocrat** [comment] 2024-05-20 11:04
Better fix committed just now. :-)
The problem is specifically related to LIKE... ESCAPE. Thanks for reporting this!

**Comment by xenocrat** [comment] 2024-05-20 22:24
I've decided to specify `|` as the default escape char for LIKE statements. _QueryBuilder.php_ and _tags.php_ have both been updated accordingly.

**Comment by xenocrat** [comment] 2024-05-21 15:02
Yes indeed, it isn't needed now that Chyrp Lite enforces `utf8mb4` character set in MySQL. But it's better not to change it, or it will cause problem with discovering existing tags. With this escaping issue resolved, all is well. :-)

**Closed as completed** 2024-05-23 01:19 UTC
Labels: bug, willfix
