### ISSUE TITLE
The blog Publish button can be clicked multiple times in a short time, which can cause multiple duplicate blog items 

### ISSUE THREAD

**Issue by shukebeta** [xenocrat/chyrp-lite#107] opened 2020-04-25 02:57 UTC
Please see the following pic

![image](https://user-images.githubusercontent.com/1399987/80269541-c7354f00-8704-11ea-8656-f002869d6140.png)

**Comment by xenocrat** [comment] 2020-04-25 10:41
Hello there.

Thanks for the report. I've tried without success to reproduce this in Firefox 75 by double-clicking the submit button and also by adding a long delay to the server response. What browser are you using?

I'm going to label this issue as "won't fix" because the browser should not allow repeat submissions of a form while a HTTP request is already in flight. I could understand the problem arising if this was an AJAX request, but it is a simple old-fashioned HTTP form submission. The browser has all the information needed to disallow another submission until the request in flight completes, times out, or is cancelled by user action.

I can prevent the behaviour you are seeing with JavaScript, but that has the potential to cause much bigger problems for the user than a double submission. I think it's better for web pages to be simple and browsers to be smart.

**Comment by shukebeta** [comment] 2020-04-25 20:29
I am using Chromium Version 80.0.3987.163 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit). Actually, it is sort of easy to reproduce on my machine. I will try to give a more detailed process to reproduce this issue today later. Thank you for your quick response :)

**Comment by shukebeta** [comment] 2020-04-25 20:38
I got the reason why I can get duplicate items. When you write an article, there're two buttons you can click which are Save & Publish. Sometimes after I pressed the Save button than I quickly realized I should press the publish button, then I press the publish button. I am usually using categories, tags in a new article.  So if you can reproduce this issue by pressing the save button first, then quickly pressing the publish button. If you like, you can quickly press the save button too, in this way you should get this issue reproduced.

**Comment by xenocrat** [comment] 2020-04-26 11:46
Thanks for persisting with this and reproducing the behaviour. I still can't reproduce this in Firefox, but I found a [discussion](https://www.sitepoint.com/community/t/multiple-requests-problem-in-chrome/6112/6) of a similar problem that indicates Firefox is the outlier here. I think it's wrong for the browser to send multiple form submissions in response to clicks like this, but it seems I need to handle it.

I have written some code to disable the other buttons in a form when one is clicked. This doesn't entirely stop a form from being submitted multiple times (there are ways other than a click to submit a form) but it should prevent the click-click-click problem.

**Closed** 2020-05-24 11:08 UTC
Labels: cannot reproduce, enhancement
