### ISSUE TITLE
Unicode emoji characters break posting functionality.

### ISSUE THREAD

**Issue by djtuBIG-MaliceX** [xenocrat/chyrp-lite#153] opened 2022-01-08 09:23 UTC
Just set up chyrp-lite v2022.01 on my personal VPS. While it all works good and all, it seems to break as soon as the post includes any Unicode emoji text content.  (eg: posts that include 🦆 😀😁😂🤣😎 etc. as entered via emoji keyboard shortcuts on most OSes nowadays)

Eg:

![image](https://user-images.githubusercontent.com/3403183/148638990-c8b3b9bb-d1f8-4ff5-90c3-4570cd5b65cc.png)

Results in:

![image](https://user-images.githubusercontent.com/3403183/148638998-c3a4ad1b-53c7-4b7f-b9f8-ef2a2ebba1ae.png)

in addition, it creates an empty article without post body content.

![image](https://user-images.githubusercontent.com/3403183/148639019-16610fde-a878-4525-b342-2ad12ff4cabe.png)

Otherwise, ASCII-only Markdown works fine.

**Comment by xenocrat** [comment] 2022-01-08 09:31
Hello there,

Thank you for the report. I will investigate and try to reproduce. What DBMS are you using: MySQL, SQLite, PostgreSQL?

**Comment by djtuBIG-MaliceX** [comment] 2022-01-08 09:38
MariaDB 10.3 on Debian Buster, which is basically MySQL.

**Comment by xenocrat** [comment] 2022-01-08 15:31
I was able to reproduce the error. I also did a bit of investigating. You need to ensure your database table has been created with one of the [utf8mb4 collations](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html) otherwise it will not be able to store the full range of Unicode characters. More details [here](https://mathiasbynens.be/notes/mysql-utf8mb4). A table collation of "utf8" is actually the half-measure utf8mb3 – fine for storing text in most languages but not good enough to store emoji.

In addition to this, I _might_ need to set the connection charset to uft8mb4 instead of utf8. The documentation is not clear on this and I'm not able to test utf8mb4 collation right now due to phpMyAdmin misbehaving, but I've committed the change to SQL.php that implements this.

**Comment by xenocrat** [comment] 2022-01-08 16:57
I got phpMyAdmin to play nicely and confirmed the fix. If you patch SQL.php from the develop branch and ensure your database, tables, and columns are all using a utf8mb4 collation then the quacken shall be released. 🦆

**Comment by djtuBIG-MaliceX** [comment] 2022-01-09 11:36
Can confirm fix after updating relevant columns `name` and `value` in `post_attributes` table, as well as replacing `SQL.php` with that in `develop` branch.

![image](https://user-images.githubusercontent.com/3403183/148680532-49e946df-b3cb-4109-89a6-c672eeb9805c.png)

**Comment by djtuBIG-MaliceX** [comment] 2022-01-09 11:48
One more thing:  Not sure if it's because I didn't switch it for everything but if I search using emoji text like so:
![image](https://user-images.githubusercontent.com/3403183/148680882-b3b2869f-1d9f-4359-b07b-53669702e612.png)

This occurs:
![image](https://user-images.githubusercontent.com/3403183/148680886-c34a5559-7e8a-4e8c-bed1-21a0874b19ec.png)

Normal search behaviour otherwise works.  The above is obviously an edge case 😅

**Comment by xenocrat** [comment] 2022-01-09 14:07
Yes I think it’s caused by the mix of collations across the posts and post_attributes tables. I’ll test that out to be sure. Thanks for reporting!

**Comment by xenocrat** [comment] 2022-01-09 22:06
Confirmed, if all tables being searched (posts, post_attributes, and pages) are fully converted to utf8mb4 then the search will succeed.

**Closed** 2022-02-16 06:17 UTC
Labels: bug, willfix
